name: Publish to AUR

on:
  release:
    types: [published]

jobs:
  aur-release:
    name: Push AUR Package
    runs-on: ubuntu-latest
    container: archlinux:latest

    steps:
      - name: Install makepkg dependencies
        run: |
          pacman -Syu --noconfirm base-devel git curl

      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set version from release tag
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

      - name: Update PKGBUILD and regenerate .SRCINFO
        run: |
          cd aur
          sed -i "s/^pkgver=.*/pkgver=${VERSION}/" PKGBUILD
          curl -L -o source.tar.gz https://github.com/${{ github.repository }}/archive/refs/tags/v${VERSION}.tar.gz
          SHA256=$(sha256sum source.tar.gz | cut -d' ' -f1)
          sed -i "s/^sha256sums=.*/sha256sums=('${SHA256}')/" PKGBUILD
          makepkg --printsrcinfo > .SRCINFO

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.AUR_SSH_KEY }}

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Push to AUR
        run: |
          git clone ssh://aur@aur.archlinux.org/passly.git aur-repo
          cp aur/PKGBUILD aur-repo/
          cp aur/.SRCINFO aur-repo/
          cd aur-repo
          git add PKGBUILD .SRCINFO
          git commit -m "Update to version ${VERSION}"
          git push
