name: Deploy to AUR

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest
    steps:
      - name: Install base-devel and git (required for makepkg)
        run: |
          pacman -Sy --noconfirm base-devel git

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Extract version from tag
        id: vars
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

      - name: Update PKGBUILD version and checksum
        run: |
          useradd -m builder
          chown -R builder:builder .
          sudo -u builder bash -c '
          sed -i "s/^pkgver=.*/pkgver=${{ env.VERSION }}/" PKGBUILD
          curl -L -o source.tar.gz https://github.com/nikooozzz/passly/archive/refs/tags/v${{ env.VERSION }}.tar.gz
          SHA256=$(sha256sum source.tar.gz | cut -d' ' -f1)
          sed -i "s/^sha256sums=.*/sha256sums=('$SHA256')/" PKGBUILD
          makepkg --printsrcinfo > .SRCINFO
          '

      - name: Push to AUR
        env:
          SSH_AUTH_SOCK: ${{ secrets.SSH_AUTH_SOCK }}
        run: |
          # Add SSH key to ssh-agent here if needed
          cd passly-aur
          git add PKGBUILD .SRCINFO
          git commit -m "Update to version ${{ env.VERSION }}"
          git push origin master
