name: Publish to AUR

on:
  release:
    types: [published]

jobs:
  aur-release:
    name: Push AUR Package
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.AUR_SSH_KEY }}

      - name: Add AUR host key
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan aur.archlinux.org >> ~/.ssh/known_hosts

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Clone AUR repository
        run: |
          git clone ssh://aur@aur.archlinux.org/passly.git aur-repo

      - name: Copy PKGBUILD and .SRCINFO
        run: |
          cp aur/PKGBUILD aur-repo/
          cp aur/.SRCINFO aur-repo/

      - name: Commit and push
        run: |
          cd aur-repo
          git add PKGBUILD .SRCINFO
          git commit -m "Update to version ${{ github.event.release.tag_name }}"
          git push
